# Generated by Django 3.2 on 2021-04-11 17:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewCommonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(max_length=500)),
                ('review_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Walker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=150)),
                ('dropoff_location', models.CharField(max_length=150)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walk_scheduler.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walk_scheduler.owner')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='Walker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walk_scheduler.walker'),
        ),
        migrations.CreateModel(
            name='WalkerReview',
            fields=[
                ('reviewcommoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='walk_scheduler.reviewcommoninfo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walk_scheduler.owner')),
                ('walker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walk_scheduler.walker')),
            ],
            bases=('walk_scheduler.reviewcommoninfo',),
        ),
        migrations.CreateModel(
            name='DogReview',
            fields=[
                ('reviewcommoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='walk_scheduler.reviewcommoninfo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walk_scheduler.walker')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walk_scheduler.dog')),
            ],
            bases=('walk_scheduler.reviewcommoninfo',),
        ),
    ]
