# Generated by Django 3.2 on 2021-04-11 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walk_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walk_scheduler.dog'),
        ),
    ]
