# Generated by Django 3.2 on 2021-04-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walk_scheduler', '0002_walk_dog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Walker',
            new_name='walker',
        ),
    ]
